name: places
description: A Flutter course project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  provider: ^6.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Regular.ttf
          weight: 400

  assets:
    - assets/icons/hotel.svg
    - assets/icons/cafe.svg
    - assets/icons/star.svg
    - assets/icons/tree.svg
    - assets/icons/restaurant.svg
    - assets/icons/musem.svg
    - assets/icons/Calendar.png
    - assets/icons/calendar_white.png
    - assets/icons/heart.png
    - assets/icons/Share.png
    - assets/icons/Union.png
    - assets/icons/Vector.png
    - assets/icons/cross.png
